name: Test build

on:
  workflow_dispatch: # enable run button on github.com
  pull_request:

jobs:
  build:
    name: Test Jekyll build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm install
      - name: Build site
        run: npm run test
        env:
          CI: true
